#Application Name
spring:
 application:
  name: Private-RestService

#Component Info
info:
  component: Private-RestService

#Aleatorioop
server:
 port: 0

#Eureka Instance ID
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

#Service Registration Method
cloud:
 services:
  registrationMethod: route

#Disable HTTP Basic Authentication
security:
  basic:
    enabled: false
